import type { Receipt } from "./types";

export const mockData: Receipt[] = [
  {
    items: [
      {
        amount: 1,
        name: "Tesco Ashbeck Still Water 2ltr",
        pricePerUnit: 0.85,
        reductionPerUnit: 0,
        totalPrice: 0.85,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Tesco British Diced Chicken Breast 400g",
        pricePerUnit: 4,
        reductionPerUnit: 0,
        totalPrice: 4,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Schwartz Paprika 30g",
        pricePerUnit: 2.25,
        reductionPerUnit: 0,
        totalPrice: 2.25,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Schwartz Oregano 6g",
        pricePerUnit: 2.25,
        reductionPerUnit: 0,
        totalPrice: 2.25,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Schwartz Mixed Herbs 7g",
        pricePerUnit: 2.25,
        reductionPerUnit: 0,
        totalPrice: 2.25,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Schwartz Mild Curry Powder 85g",
        pricePerUnit: 2.25,
        reductionPerUnit: 0,
        totalPrice: 2.25,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Tesco Large Free Range Eggs 6 Pack",
        pricePerUnit: 1.95,
        reductionPerUnit: 0,
        totalPrice: 1.95,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Frylight Olive Oil Spray 190ml",
        pricePerUnit: 3,
        reductionPerUnit: 0,
        totalPrice: 3,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Lucozade Zero Sugar Pink Lemonade 900ml",
        pricePerUnit: 1.7,
        reductionPerUnit: 0,
        totalPrice: 1.7,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Tesco Soda Water 1ltr",
        pricePerUnit: 0.9,
        reductionPerUnit: 0,
        totalPrice: 0.9,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Diet Coke 1.25l",
        pricePerUnit: 1.5,
        reductionPerUnit: 0,
        totalPrice: 1.5,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Nongshim Instant Shin Cup Noodle Soup 68g",
        pricePerUnit: 1.45,
        reductionPerUnit: 0,
        totalPrice: 1.45,
        selectedFlags: [],
      },
      {
        amount: 1,
        name: "Summer Pride Chopped Tomatoes 400g",
        pricePerUnit: 0.75,
        reductionPerUnit: 0,
        totalPrice: 0.75,
        selectedFlags: [],
      },
    ],
    metadata: {
      dateUtc: "10/03/2025 20:33:00",
      nameAddress: "South Lambeth Express",
    },
    total: 25.1,
  },
];
