import type { Metadata } from 'next';
import Navigation from '@/components/navigation';
import './tailwind.css';
import './globals.css';
import React from 'react';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body>
            <div className="flex flex-col min-h-screen">
               <Navigation />
               <div className="h-full flex-grow">{children}</div>
            </div>
         </body>
      </html>
   );
}
